"""add_tool_calls_to_messages

Revision ID: 6ec79efb1d8a
Revises: 1c17986ce493
Create Date: 2026-01-13 19:56:22.129195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec79efb1d8a'
down_revision: Union[str, Sequence[str], None] = '1c17986ce493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_calls')
    # ### end Alembic commands ###
